[package]
name = "macros_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0" # Used internally by `syn` and `quote`
futures-util = "0.3.31"

[lib]
proc-macro = true